theme: jekyll-theme-cayman

title: VAR-based meteorological data anomaly detection system
description: A novel VAR-based meteorological data analysis platform system designed for meteorological data prediction and abnomal detection. <br />
